# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a63266de9e2098c5d61c6b3eb1ad14dba417a7111aa22929e517d6d627232cf245c7dc10bf7397e99e07ba7d9900bf9baa15ae92c79805e119bed9296bec5665

test:
  secret_key_base: 3b2f3e5c3d2bf66bfae6e14343a11d1ff0462de43bbc601343ae47880653faad17b20791017fcc3ce420dd8840871e85eb055ab8361adad3ef7dfb7122f72c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
